# ruff: noqa: E501


def get_bash_completion_script(name: str = "") -> str:
    """
    Generate a bash completion script for poe.

    The script provides completion for:
    - Global CLI options (--help, -C, etc.)
    - Task names
    - Task-specific arguments (options and positionals)
    - Argument choices when defined
    - -C/--directory passthrough for alternate project paths
    """
    from pathlib import Path

    from ..app import PoeThePoet

    name = name or "poe"
    func_name = f"_{name}_complete"

    # Get global options from argparse
    app = PoeThePoet(cwd=Path().resolve())
    parser = app.ui.build_parser()

    global_opts: list[str] = []
    opts_with_values: list[str] = []
    for opt in parser._action_groups[1]._group_actions:
        if opt.help == "==SUPPRESS==":
            continue
        global_opts.extend(opt.option_strings)
        # Track options that take values
        takes_value = opt.nargs != 0 and not (
            opt.const is not None and opt.nargs is None and opt.type is None
        )
        if takes_value:
            opts_with_values.extend(opt.option_strings)

    global_opts_str = " ".join(global_opts)
    opts_with_values_str = "|".join(opts_with_values) if opts_with_values else "_NONE_"

    return f"""# Bash completion for {name}
# Generated by poethepoet

{func_name}() {{
    local cur prev words cword
    _init_completion 2>/dev/null || {{
        COMPREPLY=()
        cur="${{COMP_WORDS[COMP_CWORD]}}"
        prev="${{COMP_WORDS[COMP_CWORD-1]}}"
        words=("${{COMP_WORDS[@]}}")
        cword=$COMP_CWORD
    }}

    local target_path=""
    local task_position=""
    local potential_task=""
    local i

    # Extract target_path from -C/--directory/--root and find task position
    for ((i=1; i < ${{#words[@]}}; i++)); do
        case "${{words[i]}}" in
            -C|--directory|--root)
                if ((i+1 < ${{#words[@]}})); then
                    target_path="${{words[i+1]}}"
                    ((i++))
                fi
                ;;
            -*)
                # Skip options and their values
                case "${{words[i]}}" in
                    {opts_with_values_str})
                        ((i++))  # skip the value too
                        ;;
                esac
                ;;
            *)
                # First non-option word is the task
                if [[ -z "$task_position" ]]; then
                    task_position=$i
                    potential_task="${{words[i]}}"
                fi
                ;;
        esac
    done

    # Complete global option values (early return)
    case "$prev" in
        -C|--directory|--root)
            _filedir 2>/dev/null || COMPREPLY=($(compgen -f -- "$cur"))
            return
            ;;
        -e|--executor)
            COMPREPLY=($(compgen -W "auto poetry virtualenv simple" -- "$cur"))
            return
            ;;
    esac

    # If cursor is at or before task position, complete tasks/global options
    if [[ -z "$task_position" ]] || ((cword <= task_position)); then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "{global_opts_str}" -- "$cur"))
        else
            # Only call _list_tasks when actually completing task names
            local tasks
            tasks=$({name} _list_tasks "$target_path" 2>/dev/null)
            COMPREPLY=($(compgen -W "$tasks" -- "$cur"))
        fi
        return
    fi

    # We're past the task position - complete task args
    local current_task="$potential_task"
    local show_task_opts=false

    # If prev is an option, try to complete its value (choices)
    if [[ "$prev" == -* ]]; then
        local choices
        choices=$({name} _bash_task_arg_choices "$current_task:$prev" "$target_path" 2>/dev/null)
        if [[ "$choices" == "_BOOLEAN_" ]]; then
            # Boolean flag - doesn't take a value, show other options
            show_task_opts=true
        elif [[ -n "$choices" ]]; then
            COMPREPLY=($(compgen -W "$choices" -- "$cur"))
            return
        elif [[ "$cur" == -* ]]; then
            # User is typing another option, not a value for prev
            show_task_opts=true
        else
            # Option takes a value but has no choices - offer file completion
            _filedir 2>/dev/null || COMPREPLY=($(compgen -f -- "$cur"))
            return
        fi
    fi

    # Show task options if cur starts with - OR we just handled a boolean flag
    if [[ "$cur" == -* ]] || [[ "$show_task_opts" == true ]]; then
        local task_args
        task_args=$({name} _bash_task_args "$current_task" "$target_path" 2>/dev/null)

        # Filter out options already on command line
        local filtered_args=""
        for arg in $task_args; do
            local already_used=false
            for word in "${{words[@]}}"; do
                if [[ "$word" == "$arg" ]]; then
                    already_used=true
                    break
                fi
            done
            if [[ "$already_used" == false ]]; then
                filtered_args+=" $arg"
            fi
        done

        if [[ -n "$filtered_args" ]]; then
            COMPREPLY=($(compgen -W "$filtered_args" -- "$cur"))
            return
        fi
    fi

    # Fall back to file completion for positionals
    _filedir 2>/dev/null || COMPREPLY=($(compgen -f -- "$cur"))
}}

complete -F {func_name} {name}
"""
